FROM ghcr.io/event-horizon-technologies/chess:main
COPY . .
RUN npx tailwindcss -i ./styles/input.css -o ./styles/output.css
RUN trunk build
RUN cargo build -p server
ENTRYPOINT ./target/debug/server
